# DON'T EDIT THIS!
#
# Codecrafters relies on this file being intact to run tests successfully. Any changes
# here will not reflect when CodeCrafters tests your code, and might even cause build
# failures.
#
# DON'T EDIT THIS!

name: codecrafters-grep
version: 0.1.0.0
license: BSD3

dependencies:
  - base >= 4.19 && < 5
  - megaparsec # can help when implementing the parser
  - parser-combinators # extends megaparsec
  - containers # Set, Map, Seq
  - unordered-containers # HashSet, HashMap
  - hashable # when using your own data types with unordered-containers
  - mtl # monad transformers to help with nested monads

default-extensions:
  - BlockArguments
  - ImportQualifiedPost
  - LambdaCase
  - NamedFieldPuns
  - RecordWildCards

executables:
  codecrafters-grep-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
