slug: "grep"
name: "Build your own grep"
short_name: "grep"
release_status: "live"

description_md: |-
  Regular expressions (or Regexes) are patterns used to match character combinations in strings. In this challenge, you'll build a Regex engine from scratch by recreating grep, a CLI tool for regex-based searching.

  Along the way you'll learn about Regex syntax, character classes, quantifiers and more.

# Keep this under 70 characters
short_description_md: |-
  Learn about regex syntax: character classes, quantifiers and more

completion_percentage: 30

languages:
  - slug: "cpp"
  - slug: "csharp"
  - slug: "gleam"
  - slug: "go"
  - slug: "haskell"
  - slug: "java"
  - slug: "javascript"
  - slug: "kotlin"
  - slug: "odin"
  - slug: "php"
  - slug: "python"
  - slug: "rust"
  - slug: "typescript"
  - slug: "ruby"
    release_status: "alpha"
    alpha_tester_usernames: ["sreeram-venkitesh"]
  - slug: "zig"

marketing:
  difficulty: medium
  sample_extension_idea_title: "Lookahead assertions"
  sample_extension_idea_description: "A grep implementation that can handle lookahead assertions like x(?=y)"
  testimonials:
    - author_name: "Ananthalakshmi Sankar"
      author_description: "Automation Engineer at Apple"
      author_avatar: "https://codecrafters.io/images/external/testimonials/oxta.jpeg"
      link: "https://github.com/anu294"
      text: "There are few sites I like as much that have a step by step guide. The real-time feedback is so good, it's creepy!"

    - author_name: "Patrick Burris"
      author_description: "Senior Software Developer, CenturyLink"
      author_avatar: "https://codecrafters.io/images/external/testimonials/patrick-burris.jpeg"
      link: "https://github.com/Jumballaya"
      text: |-
        I think the instant feedback right there in the git push is really cool.
        Didn't even know that was possible!

extensions:
  - slug: "backreferences"
    name: "Backreferences"
    description_markdown: |
      In this challenge extension, you'll add support for [backreferences][1] to your Grep implementation.

      Along the way, you'll learn about how capture groups and backreferences work.
      [1]: https://learn.microsoft.com/en-us/dotnet/standard/base-types/backreference-constructs-in-regular-expressions#numbered-backreferences

  - slug: "file-search"
    name: "File Search"
    description_markdown: |
      In this challenge extension, you'll add support for searching files.

      Along the way, you'll learn about how to implement efficient file I/O, directory traversal and pattern matching on file contents.

  - slug: "quantifiers"
    name: "Quantifiers"
    description_markdown: |
      In this challenge extension, you'll add support for [quantifiers][1] to your Grep implementation.

      Along the way, you'll learn about how to implement the `*` quantifier (zero or more), and bounded quantifiers.
      [1]: https://learn.microsoft.com/en-us/dotnet/standard/base-types/quantifiers-in-regular-expressions

stages:
  - slug: "cq2"
    name: "Match a literal character"
    difficulty: very_easy
    marketing_md: |-
      In this stage, we'll handle the simplest regex possible: a single character.

      **Example:**

      `a` should match "apple", but not "dog".

  - slug: "oq2"
    name: "Match digits"
    difficulty: very_easy
    marketing_md: |-
      In this stage, we'll implement support for the `\d`
      [character class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes).

      `\d` matches any digit.

      **Example:**

      `\d` should match "1", but not "a".

  - slug: "mr9"
    name: "Match word characters"
    difficulty: very_easy
    marketing_md: |-
      In this stage, we'll implement support for the `\w`
      [character class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes).

      `\w` matches any alphanumeric character (`a-z`, `A-Z`, `0-9`) and underscore `_`.

      **Example:**

      `\w` should match "foo101", but not "$!?".

  - slug: "tl6"
    name: "Positive Character Groups"
    difficulty: medium
    marketing_md: |-
      In this stage, we'll add support for [positive character groups](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#positive-character-group--).

      Positive character groups match any character that is present within a pair of square brackets.

      **Example:**

      `[abc]` should match "apple", but not "dog".

  - slug: "rk3"
    name: "Negative Character Groups"
    difficulty: medium
    marketing_md: |-
      In this stage, we'll add support for [negative character groups](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#negative-character-group-).

      Negative character groups match any character that is not present within a pair of square brackets.

      **Example:**

      `[^abc]` should match "dog", but not "cab" (since all characters are either "a", "b" or "c").

  - slug: "sh9"
    name: "Combining Character Classes"
    difficulty: medium
    marketing_md: |-
      In this stage, we'll support patterns that combine the character classes we've seen so far.

      **Examples:**

      - `\d apple` should match "1 apple", but not "1 orange".
      - `\d\d\d apple` should match "100 apples", but not "1 apple".
      - `\d \w\w\ws` should match "3 dogs" and "4 cats" but not "1 dog" (because the "s" is not present at the end).

      This stage is significantly harder than the previous ones. You'll likely need to rework your
      implementation to process user input character-by-character instead of the whole line at once.

  - slug: "rr8"
    name: "Start of string anchor"
    difficulty: medium
    marketing_md: |-
      In this stage, we'll add support for `^`, the [Start of String or Line anchor](https://docs.microsoft.com/en-us/dotnet/standard/base-types/anchors-in-regular-expressions#start-of-string-or-line-).

      `^` doesn't match a character, it matches the start of a line.

      **Example:**

      `^log` should match "log", but not "slog".

  - slug: "ao7"
    name: "End of string anchor"
    difficulty: medium
    marketing_md: |-
      In this stage, we'll add support for `$`, the [End of String or Line anchor](https://learn.microsoft.com/en-us/dotnet/standard/base-types/anchors-in-regular-expressions#end-of-string-or-line-).

      `$` doesn't match a character, it matches the end of a line.

      **Example:**

      `dog$` should match "dog", but not "dogs".

  - slug: "fz7"
    name: "Match one or more times"
    difficulty: hard
    marketing_md: |-
      In this stage, we'll add support for `+`, the [one or more](https://docs.microsoft.com/en-us/dotnet/standard/base-types/quantifiers-in-regular-expressions#match-one-or-more-times-) quantifier.

      **Example**:

      - `a+` should match "apple" and "SaaS", but not "dog".

  - slug: "ny8"
    name: "Match zero or one times"
    difficulty: hard
    marketing_md: |-
      In this stage, we'll add support for `?`, the [zero or one](https://learn.microsoft.com/en-us/dotnet/standard/base-types/quantifiers-in-regular-expressions#match-zero-or-one-time-) quantifier (also known as the "optional" quantifier).

      **Example**:

      - `dogs?` should match "dogs" and "dog", but not "cat".

  - slug: "zb3"
    name: "Wildcard"
    difficulty: medium
    marketing_md: |-
      In this stage, we'll add support for `.`, which matches any character.

      **Example**:

      - `d.g` should match "dog", but not "cog".

  - slug: "zm7"
    name: "Alternation"
    difficulty: hard
    marketing_md: |-
      In this stage, we'll add support for the `|` keyword, which allows combining multiple patterns in an either/or fashion.

      **Example**:

      - `(cat|dog)` should match "dog" and "cat", but not "apple".

  # Backreferences

  - slug: "sb5"
    primary_extension_slug: "backreferences"
    name: "Single Backreference"
    difficulty: hard
    marketing_md: |
      In this stage, you'll add support for single backreferences. You'll implement support for `\1`.

      **Example:**
      - `(cat) and \1` should match "cat and cat", but not "cat and dog".

  - slug: "tg1"
    primary_extension_slug: "backreferences"
    name: "Multiple Backreferences"
    difficulty: medium
    marketing_md: |
      In this stage, you'll add support for multiple backreferences (`\1`, `\2` etc.) in the same pattern.

      **Example:**
      - `(\d+) (\w+) squares and \1 \2 circles` should match "3 red squares and 3 red circles" but should not match "3 red squares and 4 red circles".

  - slug: "xe5"
    primary_extension_slug: "backreferences"
    name: "Nested Backreferences"
    difficulty: hard
    marketing_md: |
      In this stage, you'll add support for nested backreferences.

      **Example:**
      - `('(cat) and \2') is the same as \1` should match "'cat and cat' is the same as 'cat and cat'".

  - slug: "dr5"
    primary_extension_slug: "file-search"
    name: "Search a single-line file"
    difficulty: medium
    marketing_md: |-
      In this stage, you'll add support for searching the contents of a file with a single line.

  - slug: "ol9"
    primary_extension_slug: "file-search"
    name: "Search a multi-line file"
    difficulty: medium
    marketing_md: |-
      In this stage, you'll add support for searching the contents of a file with multiple lines.

  - slug: "is6"
    primary_extension_slug: "file-search"
    name: "Search multiple files"
    difficulty: medium
    marketing_md: |-
      In this stage, you'll add support for searching the contents of multiple files.

  - slug: "yx6"
    primary_extension_slug: "file-search"
    name: "Recursive search"
    difficulty: hard
    marketing_md: |-
      In this stage, you'll add support for searching through files in a given directory and its subdirectories recursively with the -r flag.

  # Quantifiers
  - slug: "ai9"
    primary_extension_slug: "quantifiers"
    name: "Zero or more times"
    difficulty: hard
    marketing_md: |-
      In this stage, we'll add support for `*`, the [zero or more](https://docs.microsoft.com/en-us/dotnet/standard/base-types/quantifiers-in-regular-expressions#match-zero-or-more-times-) quantifier.

  - slug: "wy9"
    primary_extension_slug: "quantifiers"
    name: "Exact repetition"
    difficulty: hard
    marketing_md: |-
      In this stage, we'll add support for `{n}`, the [exact repetition](https://docs.microsoft.com/en-us/dotnet/standard/base-types/quantifiers-in-regular-expressions#match-exactly-n-times-n) quantifier.

  - slug: "hk3"
    primary_extension_slug: "quantifiers"
    name: "Minimum repetition"
    difficulty: hard
    marketing_md: |-
      In this stage, we'll add support for `{n,}`, the [at least m times](https://docs.microsoft.com/en-us/dotnet/standard/base-types/quantifiers-in-regular-expressions#match-at-least-n-times-n) quantifier.

  - slug: "ug0"
    primary_extension_slug: "quantifiers"
    name: "Range repetition"
    difficulty: hard
    marketing_md: |-
      In this stage, we'll add support for `{n,m}`, the [between n and m times](https://docs.microsoft.com/en-us/dotnet/standard/base-types/quantifiers-in-regular-expressions#match-between-n-and-m-times-nm) quantifier.